---
version: "3.2"

services:
  unobot:
    image: 127.0.0.1:5000/unobot
    environment:
      CONFIG_PATH: /config/ # Primarily storing the scoreboard file
      Server: irc.freenode.net
      Port: 6697 
      Nick: unoBot
      Channel: #spdcx 
      BotOps: roofis0
      UpdateScript: ./runUnoBot.sh 
      Verbose: "true"
      SSL: "true"

    volumes: 
      - /mnt/data/unobot:/config

